#!/bin/sh
#
# Startup script for the Lunarc Application Portal
#

# chkconfig: 2345 75 25
# description: LAP is a Python application server.

# Configuration section

APP_DIR=/opt/lap
PID_FILE=/var/run/lap.pid
LOG=/var/log/lap/lap_init.log

# end configuration section

# Source function library.
# Use the funtions provided by Red Hat or use our own
if [ -f /etc/rc.d/init.d/functions ]
then
	. /etc/rc.d/init.d/functions
else
	function action {
		echo "$1"
		shift
		$@
	}
	function success {
		echo -n "Success"
	}
	function failure {
		echo -n "Failed"
	}
fi

. /etc/profile.d/nordugrid.sh

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NORDUGRID_LOCATION/lib:$NORDUGRID_LOCATION/lib/python2.3/site-packages

case "$1" in
	start)
		echo -n  "Starting LAP: "
		pushd $APP_DIR > /dev/null
		LAUNCH='python ./Launch.py ThreadedAppServer'

		# run as root:
		$LAUNCH >> $LOG 2>&1 &

		echo $! > $PID_FILE
		popd > /dev/null
		success "Starting LAP"
		echo
		;;

	stop)
		echo -n "Shutting down LAP: "
		if test -f "$PID_FILE" ; then
			PID=`cat $PID_FILE`
			if kill $PID >> $LOG 2>&1 ; then
				/bin/rm $PID_FILE
				success "Shutting down LAP"
			else
				echo ""
				echo "Could not kill process $PID named in $PID_FILE. Check tail of $LOG."
				failure "Shutting down LAP"
			fi
		else
			echo ""
			echo "No LAP pid file found. Looked for $PID_FILE."
			failure "No LAP pid file found. Looked for $PID_FILE."
		fi
		echo
		;;

	cleanstart)
                echo "Cleaning up..."
                rm -f $APP_DIR/context/*.pyc
                rm -f $APP_DIR/context/Web/*.pyc
                rm -f $APP_DIR/context/Lap/*.pyc
                rm -f $APP_DIR/context/Grid/*.pyc
		$0 start
		;;

	cleanrestart)
		$0 stop
		echo "Cleaning up..."
		rm -f $APP_DIR/context/*.pyc
		rm -f $APP_DIR/context/Web/*.pyc
		rm -f $APP_DIR/context/Lap/*.pyc
		rm -f $APP_DIR/context/Grid/*.pyc
		$0 start
		;;

	restart)
		$0 stop
		$0 start
		;;

	*)
		echo "Usage: lap {start|stop|restart}"
		exit 1

esac

exit 0
