# -*- coding: iso-8859-15 -*-
# generated by wxGlade HG on Thu May 28 11:43:12 2009

#
# AddOutputFileDialog - Dialog for adding outputfiles.
#
# Copyright (C) 2008-2009 Jonas Lindemann
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#

"""
Defines an dialog for adding output files.
"""

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class AddOutputFileDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: AddOutputFileDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.outputFilenameLabel = wx.StaticText(self, -1, "Filename")
        self.outputFilenameText = wx.TextCtrl(self, -1, "")
        self.outputFilenameURLLabel = wx.StaticText(self, -1, "URL")
        self.outputFilenameURLText = wx.TextCtrl(self, -1, "")
        self.button_1 = wx.Button(self, wx.ID_OK, "")
        self.button_2 = wx.Button(self, wx.ID_CANCEL, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade
        
        self.__initDialog()

    def __set_properties(self):
        # begin wxGlade: AddOutputFileDialog.__set_properties
        self.SetTitle("Add output file")
        self.SetSize((400, 119))
        self.outputFilenameLabel.SetMinSize((100, -1))
        self.outputFilenameText.SetMinSize((-1, 27))
        self.outputFilenameText.SetFocus()
        self.outputFilenameURLLabel.SetMinSize((100, -1))
        self.outputFilenameURLText.SetMinSize((-1, 27))
        self.button_1.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: AddOutputFileDialog.__do_layout
        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11.Add(self.outputFilenameLabel, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 5)
        sizer_11.Add(self.outputFilenameText, 1, wx.ADJUST_MINSIZE, 0)
        sizer_10.Add(sizer_11, 0, wx.ALL|wx.EXPAND, 4)
        sizer_12.Add(self.outputFilenameURLLabel, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 5)
        sizer_12.Add(self.outputFilenameURLText, 1, wx.ADJUST_MINSIZE, 0)
        sizer_10.Add(sizer_12, 0, wx.ALL|wx.EXPAND, 4)
        sizer_13.Add(self.button_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_13.Add(self.button_2, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10.Add(sizer_13, 0, wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_HORIZONTAL, 8)
        self.SetSizer(sizer_10)
        self.Layout()
        # end wxGlade
        
    def __initDialog(self):
        self.__outputFilename = ""
        self.__outputFilenameURL = ""
        
    def setOutputFilename(self, filename):
        self.__outputFilename = ""
        self.outputFilnameText.SetValue(filename)
        
    def getOutputFilename(self):
        self.__outputFilename = self.outputFilenameText.GetValue()
        return self.__outputFilename
    
    def setOutputFilenameURL(self, filename):
        self.__outputFilenameURL = ""
        self.outputFilnameURLText.SetValue(filename)
        
    def getOutputFilenameURL(self):
        self.__outputFilenameURL = self.outputFilenameText.GetValue()
        return self.__outputFilenameURL
        
    outputFilename = property(getOutputFilename, setOutputFilename)
    outputFilenameURL = property(getOutputFilenameURL, setOutputFilenameURL)

# end of class AddOutputFileDialog


