# -*- coding: iso-8859-15 -*-
# generated by wxGlade HG on Fri Jul  3 20:15:50 2009

#
# ArcSplash main window class
#
# Copyright (C) 2008-2010 Jonas Lindemann
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

import os

class ArcSplash(wx.Frame):
    """
    Splash window class
    
    Implements the ArcGui splash window.
    """
    def __init__(self, *args, **kwds):
        # begin wxGlade: ArcSplash.__init__
        kwds["style"] = wx.CAPTION|wx.CLOSE_BOX|wx.STAY_ON_TOP
        wx.Frame.__init__(self, *args, **kwds)
        self.splashBitmap = wx.StaticBitmap(self, -1, wx.NullBitmap)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade
        
        self.__initWindow()

    def __set_properties(self):
        # begin wxGlade: ArcSplash.__set_properties
        self.SetTitle("About ArcGUI 0.2.1")
        self.SetSize((400, -1))
        self.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.splashBitmap.SetMinSize((400,300))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ArcSplash.__do_layout
        sizer_34 = wx.BoxSizer(wx.VERTICAL)
        sizer_34.Add(self.splashBitmap, 1, wx.SHAPED, 0)
        self.SetSizer(sizer_34)
        sizer_34.SetSizeHints(self)
        self.Layout()
        self.Centre()
        # end wxGlade
        
    def __initWindow(self):
        """
        Window initialisation.
        
        Loads the splash image from the ArcGui install directory. Starts a timer for closing the window.
        """
        if os.environ.has_key("ARCGUI_LOCATION"):
            arcGuiLocation = os.environ["ARCGUI_LOCATION"]
            if os.path.exists(arcGuiLocation):
                self.splashBitmap.SetBitmap(wx.Bitmap(os.path.join(arcGuiLocation,"images/ARClogo.png"), wx.BITMAP_TYPE_ANY))
                
        self.__splashTimerID = 100  
        self.__splashTimer = wx.Timer(self, self.__splashTimerID)  # message will be sent to the panel
        wx.EVT_TIMER(self, self.__splashTimerID, self.onSplashTimer)
        
        self.__splashTimer.Start(4000)
        
    def onSplashTimer(self, event):
        """
        Event method responding the splash timer.
        
        Closes the window.
        """
        self.Destroy()


# end of class ArcSplash


