# -*- coding: iso-8859-15 -*-
# generated by wxGlade HG on Mon Jul  6 15:48:44 2009

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class ClientSettingsDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ClientSettingsDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.settingsNotebook = wx.Notebook(self, -1, style=0)
        self.preferredPane = wx.Panel(self.settingsNotebook, -1)
        self.rejectedPane = wx.Panel(self.settingsNotebook, -1)
        self.generalPane = wx.Panel(self.settingsNotebook, -1)
        self.timeoutLabel = wx.StaticText(self.generalPane, -1, "Timeout (s)")
        self.timeOutText = wx.TextCtrl(self.generalPane, -1, "40")
        self.brokerLabel = wx.StaticText(self.generalPane, -1, "Broker")
        self.brokerCombo = wx.ComboBox(self.generalPane, -1, choices=["RandomBroker"], style=wx.CB_DROPDOWN)
        self.rejectedClustersList = wx.ListBox(self.rejectedPane, -1, choices=[])
        self.addRejectedButton = wx.Button(self.rejectedPane, -1, "Add...")
        self.removeRejectedButton = wx.Button(self.rejectedPane, -1, "Remove")
        self.clearRejectedButton = wx.Button(self.rejectedPane, -1, "Clear")
        self.preferredClustersList = wx.ListBox(self.preferredPane, -1, choices=[])
        self.addPreferredButton = wx.Button(self.preferredPane, -1, "Add...")
        self.removePreferredButton = wx.Button(self.preferredPane, -1, "Remove")
        self.clearPreferredButton = wx.Button(self.preferredPane, -1, "Clear")
        self.okButton = wx.Button(self, wx.ID_OK, "")
        self.cancelButton = wx.Button(self, wx.ID_CANCEL, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade
        
        self.__initDialog()

    def __set_properties(self):
        # begin wxGlade: ClientSettingsDialog.__set_properties
        self.SetTitle("Client settings")
        self.SetSize((459, 316))
        self.timeoutLabel.SetMinSize((120, -1))
        self.brokerLabel.SetMinSize((120, -1))
        self.brokerCombo.SetSelection(-1)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ClientSettingsDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_18_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_19_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_18 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_19 = wx.BoxSizer(wx.VERTICAL)
        sizer_15 = wx.BoxSizer(wx.VERTICAL)
        sizer_17 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_16 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_16.Add(self.timeoutLabel, 0, wx.LEFT|wx.RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_16.Add(self.timeOutText, 0, wx.ADJUST_MINSIZE, 0)
        sizer_15.Add(sizer_16, 0, wx.ALL|wx.EXPAND, 5)
        sizer_17.Add(self.brokerLabel, 0, wx.LEFT|wx.RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_17.Add(self.brokerCombo, 0, wx.ADJUST_MINSIZE, 0)
        sizer_15.Add(sizer_17, 0, wx.ALL|wx.EXPAND, 5)
        self.generalPane.SetSizer(sizer_15)
        sizer_18.Add(self.rejectedClustersList, 1, wx.ALL|wx.EXPAND|wx.ADJUST_MINSIZE, 5)
        sizer_19.Add(self.addRejectedButton, 0, wx.BOTTOM|wx.ADJUST_MINSIZE, 5)
        sizer_19.Add(self.removeRejectedButton, 0, wx.BOTTOM|wx.ADJUST_MINSIZE, 5)
        sizer_19.Add(self.clearRejectedButton, 0, wx.ADJUST_MINSIZE, 0)
        sizer_18.Add(sizer_19, 0, wx.ALL|wx.EXPAND, 5)
        self.rejectedPane.SetSizer(sizer_18)
        sizer_18_copy.Add(self.preferredClustersList, 1, wx.ALL|wx.EXPAND|wx.ADJUST_MINSIZE, 5)
        sizer_19_copy.Add(self.addPreferredButton, 0, wx.BOTTOM|wx.ADJUST_MINSIZE, 5)
        sizer_19_copy.Add(self.removePreferredButton, 0, wx.BOTTOM|wx.ADJUST_MINSIZE, 5)
        sizer_19_copy.Add(self.clearPreferredButton, 0, wx.ADJUST_MINSIZE, 0)
        sizer_18_copy.Add(sizer_19_copy, 0, wx.ALL|wx.EXPAND, 5)
        self.preferredPane.SetSizer(sizer_18_copy)
        self.settingsNotebook.AddPage(self.generalPane, "General")
        self.settingsNotebook.AddPage(self.rejectedPane, "Rejected clusters")
        self.settingsNotebook.AddPage(self.preferredPane, "Preferred clusters")
        sizer_1.Add(self.settingsNotebook, 1, wx.ALL|wx.EXPAND, 5)
        sizer_14.Add(self.okButton, 0, wx.RIGHT|wx.ADJUST_MINSIZE, 5)
        sizer_14.Add(self.cancelButton, 0, wx.ADJUST_MINSIZE, 0)
        sizer_1.Add(sizer_14, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 3)
        self.SetSizer(sizer_1)
        self.Layout()
        self.Centre()
        # end wxGlade
        
    def __initDialog(self):
        self.__userConfig = None
        
    def setUserConfig(self, userConfig):
        """
        text boxes with relevant information
        """
        self.__userConfig = userConfig
        
        timeOutValue = self.__userConfig.ConfTree().Get("TimeOut")
        broker = self.__userConfig.ConfTree().Get("Broker").Get("Name")
        
        print "broker=",broker
        
        if timeOutValue!="":
            self.timeOutText.SetValue(str(timeOutValue))
            
        if broker!="":
            self.brokerCombo.SetValue(str(broker))    
                
    def getUserConfig(self):
        """
        Returns the current value of the userConfig property.
        """
        return self.__userConfig
    
    def getTimeOut(self):
        return int(self.timeOutText.GetValue())
        
    def getBroker(self):
        return str(self.brokerCombo.GetValue())
    
    userConfig = property(getUserConfig, setUserConfig)
    timeOut = property(getTimeOut)
    broker = property(getBroker)


# end of class ClientSettingsDialog


