# -*- coding: utf-8 -*-
# generated by wxGlade HG on Sat Apr  3 15:46:47 2010

import wx
from arcjobtool.CertRequestWindow import CertRequestWindow

import os

class CertRequestApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        certRequestWindow = CertRequestWindow(None, -1, "")
        self.SetTopWindow(certRequestWindow)
        certRequestWindow.Show()
        return 1

# end of class CertRequestApp

if os.environ.has_key("ARCJOBTOOL_LIB"):
    CertRequestApp = CertRequestApp(0)
    CertRequestApp.MainLoop()
