# -*- coding: iso-8859-15 -*-
# generated by wxGlade HG on Mon Jul  6 19:39:07 2009

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

import arc

class DefaultServicesDialog(wx.Dialog, object):
    def __init__(self, *args, **kwds):
        # begin wxGlade: DefaultServicesDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.servicesTabs = wx.Notebook(self, -1, style=0)
        self.notebook_2_pane_2 = wx.Panel(self.servicesTabs, -1)
        self.notebook_2_pane_1 = wx.Panel(self.servicesTabs, -1)
        self.defaultServicesList = wx.ListBox(self.notebook_2_pane_1, -1, choices=[])
        self.addServiceButton = wx.Button(self.notebook_2_pane_1, -1, "Add...")
        self.modifyServiceButton = wx.Button(self.notebook_2_pane_1, -1, "Modify...")
        self.removeServiceButton = wx.Button(self.notebook_2_pane_1, -1, "Remove")
        self.clearServicesButton = wx.Button(self.notebook_2_pane_1, -1, "Clear")
        self.rejectedServicesList = wx.ListBox(self.notebook_2_pane_2, -1, choices=[])
        self.addRejectedServiceButton = wx.Button(self.notebook_2_pane_2, -1, "Add...")
        self.modifyRejectedServiceButton = wx.Button(self.notebook_2_pane_2, -1, "Modify...")
        self.removeRejectedServiceButton = wx.Button(self.notebook_2_pane_2, -1, "Remove")
        self.clearRejectedServicesButton = wx.Button(self.notebook_2_pane_2, -1, "Clear")
        self.okButton = wx.Button(self, -1, "OK")
        self.cancelButton = wx.Button(self, -1, "Cancel")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.onAddService, self.addServiceButton)
        self.Bind(wx.EVT_BUTTON, self.onModifyService, self.modifyServiceButton)
        self.Bind(wx.EVT_BUTTON, self.onRemoveService, self.removeServiceButton)
        self.Bind(wx.EVT_BUTTON, self.onClearServices, self.clearServicesButton)
        self.Bind(wx.EVT_BUTTON, self.onAddRejectedService, self.addRejectedServiceButton)
        self.Bind(wx.EVT_BUTTON, self.onModifyRejectedService, self.modifyRejectedServiceButton)
        self.Bind(wx.EVT_BUTTON, self.onRemoveRejectedService, self.removeRejectedServiceButton)
        self.Bind(wx.EVT_BUTTON, self.onClearRejectedServices, self.clearRejectedServicesButton)
        self.Bind(wx.EVT_BUTTON, self.onOK, self.okButton)
        self.Bind(wx.EVT_BUTTON, self.onCancel, self.cancelButton)
        # end wxGlade
        
        self.__initDialog()

    def __set_properties(self):
        # begin wxGlade: DefaultServicesDialog.__set_properties
        self.SetTitle("Default services")
        self.SetSize((457, 315))
        self.okButton.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: DefaultServicesDialog.__do_layout
        sizer_28 = wx.BoxSizer(wx.VERTICAL)
        sizer_31 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_29_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_30_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_29 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_30 = wx.BoxSizer(wx.VERTICAL)
        sizer_29.Add(self.defaultServicesList, 1, wx.ALL|wx.EXPAND, 4)
        sizer_30.Add(self.addServiceButton, 0, 0, 0)
        sizer_30.Add(self.modifyServiceButton, 0, 0, 0)
        sizer_30.Add(self.removeServiceButton, 0, 0, 0)
        sizer_30.Add(self.clearServicesButton, 0, 0, 0)
        sizer_29.Add(sizer_30, 0, wx.ALL|wx.EXPAND, 4)
        self.notebook_2_pane_1.SetSizer(sizer_29)
        sizer_29_copy.Add(self.rejectedServicesList, 1, wx.ALL|wx.EXPAND, 4)
        sizer_30_copy.Add(self.addRejectedServiceButton, 0, 0, 0)
        sizer_30_copy.Add(self.modifyRejectedServiceButton, 0, 0, 0)
        sizer_30_copy.Add(self.removeRejectedServiceButton, 0, 0, 0)
        sizer_30_copy.Add(self.clearRejectedServicesButton, 0, 0, 0)
        sizer_29_copy.Add(sizer_30_copy, 0, wx.ALL|wx.EXPAND, 4)
        self.notebook_2_pane_2.SetSizer(sizer_29_copy)
        self.servicesTabs.AddPage(self.notebook_2_pane_1, "Default")
        self.servicesTabs.AddPage(self.notebook_2_pane_2, "Rejected")
        sizer_28.Add(self.servicesTabs, 1, wx.LEFT|wx.RIGHT|wx.TOP|wx.EXPAND, 5)
        sizer_31.Add(self.okButton, 0, 0, 0)
        sizer_31.Add(self.cancelButton, 0, 0, 0)
        sizer_28.Add(sizer_31, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 4)
        self.SetSizer(sizer_28)
        self.Layout()
        self.Centre()
        # end wxGlade
        
    def __initDialog(self):
        self.__arcGuiConfig = None
        self.__serviceList = []
        
    def __updateListBox(self):
        print "updateListBox"
        if self.__arcGuiConfig!=None:
            self.defaultServicesList.Clear()
            for serviceName in self.__serviceList:
                self.defaultServicesList.Append(serviceName)               
            
    def setArcGuiConfig(self, arcGuiConfig):
        print "setArcGuiConfig"
        self.__arcGuiConfig = arcGuiConfig
        self.__serviceList = list(self.__arcGuiConfig.defaultServices)
        self.__updateListBox()
        
    def getArcGuiConfig(self):
        return self.__arcGuiConfig

    def onAddService(self, event): # wxGlade: DefaultServicesDialog.<event_handler>
        serviceUrl = wx.GetTextFromUser("Add new service", "Default services", "", centre = True)
        if serviceUrl!="":
            self.__serviceList.append(serviceUrl)
            self.__updateListBox()
        else:
            wx.MessageBox("Not a valid URL", "Default services")

    def onRemoveService(self, event): # wxGlade: DefaultServicesDialog.<event_handler>
        if self.defaultServicesList.GetSelection()>=0:
            del self.__serviceList[self.defaultServicesList.GetSelection()]
            self.defaultServicesList.Delete(self.defaultServicesList.GetSelection())
            self.__updateListBox()
        else:
            wx.MessageBox("Please select a service in the list.")

    def onClearServices(self, event): # wxGlade: DefaultServicesDialog.<event_handler>
        self.defaultServicesList.Clear()
        self.__serviceList = []
        self.__updateListBox()

    def onModifyService(self, event): # wxGlade: DefaultServicesDialog.<event_handler>
        selectedItem = self.defaultServicesList.GetSelection()
        serviceUrl = self.defaultServicesList.GetString(selectedItem)
        serviceUrl = wx.GetTextFromUser("Modify service", "Default services", serviceUrl, centre = True)
        if serviceUrl!="":
            self.defaultServicesList.SetString(selectedItem, serviceUrl)
            self.__serviceList[selectedItem] = serviceUrl
                
    def getServiceList(self):
        return self.defaultServicesList.GetStrings()
                
    def onOK(self, event): # wxGlade: DefaultServicesDialog.<event_handler>
        self.__arcGuiConfig.defaultServices = self.__serviceList
        self.__arcGuiConfig.update()
        self.Close()

    def onCancel(self, event): # wxGlade: DefaultServicesDialog.<event_handler>
        self.Close()
        
    def onAddRejectedService(self, event): # wxGlade: DefaultServicesDialog.<event_handler>
        print "Event handler `onAddRejectedService' not implemented"
        event.Skip()

    def onModifyRejectedService(self, event): # wxGlade: DefaultServicesDialog.<event_handler>
        print "Event handler `onModifyRejectedService' not implemented"
        event.Skip()

    def onRemoveRejectedService(self, event): # wxGlade: DefaultServicesDialog.<event_handler>
        print "Event handler `onRemoveRejectedService' not implemented"
        event.Skip()

    def onClearRejectedServices(self, event): # wxGlade: DefaultServicesDialog.<event_handler>
        print "Event handler `onClearRejectedServices' not implemented"
        event.Skip()

    arcGuiConfig = property(getArcGuiConfig, setArcGuiConfig)

# end of class DefaultServicesDialog


