# -*- coding: iso-8859-15 -*-
# generated by wxGlade HG on Sun Feb 28 16:49:12 2010

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class JobPropertiesDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: JobPropertiesDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.THICK_FRAME|wx.STAY_ON_TOP
        wx.Dialog.__init__(self, *args, **kwds)
        self.mainPanel = wx.Panel(self, -1)
        self.jobPropertiesList = wx.ListCtrl(self.mainPanel, -1, style=wx.LC_REPORT|wx.LC_HRULES|wx.LC_VRULES|wx.SUNKEN_BORDER)
        self.closeButton = wx.Button(self, -1, "Close")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.onClose, self.closeButton)
        # end wxGlade
        
        self.__initDialog()        

    def __set_properties(self):
        # begin wxGlade: JobPropertiesDialog.__set_properties
        self.SetTitle("Job properties")
        self.jobPropertiesList.SetMinSize((347, 467))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: JobPropertiesDialog.__do_layout
        mainSizer = wx.BoxSizer(wx.VERTICAL)
        buttonSizer = wx.BoxSizer(wx.HORIZONTAL)
        mainPanelSizer = wx.BoxSizer(wx.VERTICAL)
        mainPanelSizer.Add(self.jobPropertiesList, 1, wx.EXPAND, 0)
        self.mainPanel.SetSizer(mainPanelSizer)
        mainSizer.Add(self.mainPanel, 1, wx.ALL|wx.EXPAND, 4)
        buttonSizer.Add(self.closeButton, 0, 0, 0)
        mainSizer.Add(buttonSizer, 0, wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_HORIZONTAL, 4)
        self.SetSizer(mainSizer)
        mainSizer.Fit(self)
        self.Layout()
        # end wxGlade
        
    def __initDialog(self):
        self.__jobDict = None
        
    def __fillListControl(self):
        self.jobPropertiesList.ClearAll()
        
        self.jobPropertiesList.InsertColumn(0, "Property")
        self.jobPropertiesList.InsertColumn(1, "Value")
                       
        row = 0
        
        properties = self.__jobDict[self.__jobId].keys()
        properties.sort()
              
        for propertyName in properties:
            self.jobPropertiesList.InsertStringItem(row,propertyName)
            self.jobPropertiesList.SetStringItem(row,1,str(self.__jobDict[self.__jobId][propertyName]))
            
            row += 1
            
        self.jobPropertiesList.SetColumnWidth(0, wx.LIST_AUTOSIZE)
        self.jobPropertiesList.SetColumnWidth(1, wx.LIST_AUTOSIZE)
        
    def getJobDict(self):
        return self.__jobDict
    
    def setJobDict(self, jobDict):
        self.__jobDict = jobDict
        
    def getJobId(self):
        return self.__jobId
    
    def setJobId(self, jobId):
        self.__jobId = jobId
        self.__fillListControl()

    def onClose(self, event): # wxGlade: JobPropertiesDialog.<event_handler>
        self.Close()
        
    jobDict = property(getJobDict, setJobDict)
    jobId = property(getJobId, setJobId)

# end of class JobPropertiesDialog


